---
driver:
  name: vagrant

provisioner:
  name: shell

platforms:
  - name: krastin/xenial-consul
    driver:
      box: xenial-consul
      provider: virtualbox

verifier:
  name: inspec

suites:
  - name: default
